
(define tax_rate 0.065)
(define (cash_register)
  (display "Scheme Point-of-Sale")
  (newline)
  (display "Start transaction (exit with 0):")
  (newline)
  (display "Enter amount: ")
  (let ((val (read))) (calc val 0))
) 

(define (calc input subtotal)
  (cond
    ((eq? input -1)
      (display "Subtotal: ")
      (display subtotal)
      (newline)
      (display "Tax: ")
      (display (* tax_rate subtotal))
      (newline)
      (display "Total: ")
      (display (+ subtotal (* tax_rate subtotal))) #t)
    (else (display "Enter amount: ")
      (let ((val (read)))(calc val (+ input subtotal)))
    )
  )
)
